[package]
name = "mrust_1"
version = "0.1.0"
edition = "2024"

[features]
req1 = []
req2 = []
ai = []

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] } # Thư viện gọi HTTP
serde = { version = "1.0", features = ["derive"] }  # Thư viện Serialize/Deserialize dữ liệu
serde_json = "1.0"           
rig-core = "0.7"
colored = "2.1"
regex = "1.10"
syntect = { version = "5.2", features = ["default-syntaxes", "default-themes"] }